from classi import Bottiglia,BottigliaConTappo            #importa la classe dal file classi.py
b= Bottiglia(500)
print(b.capacità)
print(b.quantità)
print(b)
b.riempi (200)
print(b)
b.riempi (700)
print(b)
b.svuota (400)
print(b)
b.svuota (300)
print(b)

b2= BottigliaConTappo(1500)
print("situazione iniziale "+str(b2))
b2.chiudi()
print("dopo chiusura tappo "+str(b2))
b2.riempi(1500)
print("situazione dopo riempimento "+str(b2))
